### ISSUE TITLE
After sorting, empty strings are at the beginning of the sorted array

### ISSUE THREAD

**Issue by vladshcherbin** [roryrjb/ckeys#1]
Code:

```js
const ckeys = require('ckeys')

const emptyStringTestArray = [
  { title: 'b' },
  { title: '' },
  { title: 'a' }
]

console.log(emptyStringTestArray.sort(ckeys('title')))
```

Output:

```js
[
  { title: '' },
  { title: 'a' },
  { title: 'b' }
]
```

Expected output:

```js
[
  { title: 'a' },
  { title: 'b' },
  { title: '' }
]
```

Since it's sorting by string alphabetically, I'd expect to see empty string at the end of the array, not at the beginning.

**Comment by roryrjb** [comment]
@vladshcherbin this may make more sense, but sorting primitive values behaves in this way, e.g.:

```javascript
['c', 'b', '', 'a'].sort() // => [ '', 'a', 'b', 'c' ]
```

...and I don't want to change that based on this expectation.
